# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\systemTool\python\ptCacheTools\cacheOpenNote.ui'
#
# Created: Tue Jun 10 18:55:16 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_OpenNoteWindows(object):
    def setupUi(self, OpenNoteWindows):
        OpenNoteWindows.setObjectName(_fromUtf8("OpenNoteWindows"))
        OpenNoteWindows.resize(300, 526)
        self.centralwidget = QtGui.QWidget(OpenNoteWindows)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 281, 101))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 46, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 51, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 61, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.project_label = QtGui.QLabel(self.frame)
        self.project_label.setGeometry(QtCore.QRect(90, 10, 171, 16))
        self.project_label.setObjectName(_fromUtf8("project_label"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 46, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.episode_label = QtGui.QLabel(self.frame)
        self.episode_label.setGeometry(QtCore.QRect(90, 30, 171, 16))
        self.episode_label.setObjectName(_fromUtf8("episode_label"))
        self.sequence_label = QtGui.QLabel(self.frame)
        self.sequence_label.setGeometry(QtCore.QRect(90, 50, 141, 16))
        self.sequence_label.setObjectName(_fromUtf8("sequence_label"))
        self.shot_label = QtGui.QLabel(self.frame)
        self.shot_label.setGeometry(QtCore.QRect(90, 70, 151, 16))
        self.shot_label.setObjectName(_fromUtf8("shot_label"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 120, 281, 401))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.submit_pushButton = QtGui.QPushButton(self.frame_4)
        self.submit_pushButton.setGeometry(QtCore.QRect(120, 360, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.submit_pushButton.setPalette(palette)
        self.submit_pushButton.setObjectName(_fromUtf8("submit_pushButton"))
        self.label_10 = QtGui.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(10, 160, 51, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.openNote_plainTextEdit = QtGui.QPlainTextEdit(self.frame_4)
        self.openNote_plainTextEdit.setGeometry(QtCore.QRect(10, 180, 261, 121))
        self.openNote_plainTextEdit.setObjectName(_fromUtf8("openNote_plainTextEdit"))
        self.label_11 = QtGui.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 11, 51, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.from_lineEdit = QtGui.QLineEdit(self.frame_4)
        self.from_lineEdit.setGeometry(QtCore.QRect(150, 320, 121, 20))
        self.from_lineEdit.setText(_fromUtf8(""))
        self.from_lineEdit.setObjectName(_fromUtf8("from_lineEdit"))
        self.label_12 = QtGui.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(100, 320, 51, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.problem_comboBox = QtGui.QComboBox(self.frame_4)
        self.problem_comboBox.setGeometry(QtCore.QRect(80, 40, 131, 22))
        self.problem_comboBox.setObjectName(_fromUtf8("problem_comboBox"))
        self.cache_label = QtGui.QLabel(self.frame_4)
        self.cache_label.setGeometry(QtCore.QRect(90, 10, 151, 16))
        self.cache_label.setObjectName(_fromUtf8("cache_label"))
        self.label_14 = QtGui.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.action_comboBox = QtGui.QComboBox(self.frame_4)
        self.action_comboBox.setGeometry(QtCore.QRect(80, 70, 131, 22))
        self.action_comboBox.setObjectName(_fromUtf8("action_comboBox"))
        self.label_15 = QtGui.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(10, 100, 61, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.priority_comboBox = QtGui.QComboBox(self.frame_4)
        self.priority_comboBox.setGeometry(QtCore.QRect(80, 100, 131, 22))
        self.priority_comboBox.setObjectName(_fromUtf8("priority_comboBox"))
        self.email_checkBox = QtGui.QCheckBox(self.frame_4)
        self.email_checkBox.setGeometry(QtCore.QRect(80, 130, 70, 17))
        self.email_checkBox.setChecked(True)
        self.email_checkBox.setObjectName(_fromUtf8("email_checkBox"))
        self.shotgun_checkBox = QtGui.QCheckBox(self.frame_4)
        self.shotgun_checkBox.setGeometry(QtCore.QRect(150, 130, 70, 17))
        self.shotgun_checkBox.setChecked(True)
        self.shotgun_checkBox.setObjectName(_fromUtf8("shotgun_checkBox"))
        self.label_16 = QtGui.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(10, 130, 61, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        OpenNoteWindows.setCentralWidget(self.centralwidget)

        self.retranslateUi(OpenNoteWindows)
        QtCore.QMetaObject.connectSlotsByName(OpenNoteWindows)

    def retranslateUi(self, OpenNoteWindows):
        OpenNoteWindows.setWindowTitle(QtGui.QApplication.translate("OpenNoteWindows", "Open Note Tool v.1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OpenNoteWindows", "Project : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("OpenNoteWindows", "Episode : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("OpenNoteWindows", "Sequence : ", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("OpenNoteWindows", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("OpenNoteWindows", "Shot : ", None, QtGui.QApplication.UnicodeUTF8))
        self.episode_label.setText(QtGui.QApplication.translate("OpenNoteWindows", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.sequence_label.setText(QtGui.QApplication.translate("OpenNoteWindows", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_label.setText(QtGui.QApplication.translate("OpenNoteWindows", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_pushButton.setText(QtGui.QApplication.translate("OpenNoteWindows", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("OpenNoteWindows", "Note : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("OpenNoteWindows", "Task :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("OpenNoteWindows", "From : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("OpenNoteWindows", "Problems : ", None, QtGui.QApplication.UnicodeUTF8))
        self.cache_label.setText(QtGui.QApplication.translate("OpenNoteWindows", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("OpenNoteWindows", "Action : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("OpenNoteWindows", "Priority : ", None, QtGui.QApplication.UnicodeUTF8))
        self.email_checkBox.setText(QtGui.QApplication.translate("OpenNoteWindows", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.shotgun_checkBox.setText(QtGui.QApplication.translate("OpenNoteWindows", "Shotgun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("OpenNoteWindows", "Send to : ", None, QtGui.QApplication.UnicodeUTF8))

