# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\systemTool\python\ptCacheTools\importUI.ui'
#
# Created: Mon Jun 16 15:36:49 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ImportCacheWindow(object):
    def setupUi(self, ImportCacheWindow):
        ImportCacheWindow.setObjectName(_fromUtf8("ImportCacheWindow"))
        ImportCacheWindow.resize(494, 845)
        self.centralwidget = QtGui.QWidget(ImportCacheWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 9, 451, 161))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 46, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 51, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 61, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 46, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.project_comboBox = QtGui.QComboBox(self.frame)
        self.project_comboBox.setGeometry(QtCore.QRect(80, 15, 151, 22))
        self.project_comboBox.setObjectName(_fromUtf8("project_comboBox"))
        self.episode_comboBox = QtGui.QComboBox(self.frame)
        self.episode_comboBox.setGeometry(QtCore.QRect(80, 45, 151, 22))
        self.episode_comboBox.setObjectName(_fromUtf8("episode_comboBox"))
        self.sequence_comboBox = QtGui.QComboBox(self.frame)
        self.sequence_comboBox.setGeometry(QtCore.QRect(80, 75, 151, 22))
        self.sequence_comboBox.setObjectName(_fromUtf8("sequence_comboBox"))
        self.shot_comboBox = QtGui.QComboBox(self.frame)
        self.shot_comboBox.setGeometry(QtCore.QRect(80, 105, 151, 22))
        self.shot_comboBox.setObjectName(_fromUtf8("shot_comboBox"))
        self.frame_6 = QtGui.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(250, 10, 191, 141))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.showInfo_pushButton = QtGui.QPushButton(self.frame_6)
        self.showInfo_pushButton.setGeometry(QtCore.QRect(10, 110, 171, 21))
        self.showInfo_pushButton.setObjectName(_fromUtf8("showInfo_pushButton"))
        self.icon_label = QtGui.QLabel(self.frame_6)
        self.icon_label.setGeometry(QtCore.QRect(20, 5, 151, 101))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.icon_label.setFont(font)
        self.icon_label.setObjectName(_fromUtf8("icon_label"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 180, 451, 391))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 101, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cache_comboBox = QtGui.QComboBox(self.frame_2)
        self.cache_comboBox.setGeometry(QtCore.QRect(120, 15, 171, 22))
        self.cache_comboBox.setObjectName(_fromUtf8("cache_comboBox"))
        self.asset_tableWidget = QtGui.QTableWidget(self.frame_2)
        self.asset_tableWidget.setGeometry(QtCore.QRect(10, 50, 431, 192))
        self.asset_tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.asset_tableWidget.setObjectName(_fromUtf8("asset_tableWidget"))
        self.asset_tableWidget.setColumnCount(4)
        self.asset_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(3, item)
        self.asset_tableWidget.horizontalHeader().setVisible(True)
        self.asset_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.asset_tableWidget.horizontalHeader().setDefaultSectionSize(106)
        self.asset_tableWidget.horizontalHeader().setHighlightSections(True)
        self.asset_tableWidget.verticalHeader().setVisible(True)
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 250, 431, 131))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.removeAsset_pushButton = QtGui.QPushButton(self.frame_3)
        self.removeAsset_pushButton.setGeometry(QtCore.QRect(200, 40, 131, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(156, 70, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(156, 70, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(156, 70, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.removeAsset_pushButton.setPalette(palette)
        self.removeAsset_pushButton.setObjectName(_fromUtf8("removeAsset_pushButton"))
        self.rebuildAsset_pushButton = QtGui.QPushButton(self.frame_3)
        self.rebuildAsset_pushButton.setGeometry(QtCore.QRect(10, 40, 181, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.rebuildAsset_pushButton.setPalette(palette)
        self.rebuildAsset_pushButton.setObjectName(_fromUtf8("rebuildAsset_pushButton"))
        self.importCache_pushButton = QtGui.QPushButton(self.frame_3)
        self.importCache_pushButton.setGeometry(QtCore.QRect(10, 80, 411, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.importCache_pushButton.setPalette(palette)
        self.importCache_pushButton.setObjectName(_fromUtf8("importCache_pushButton"))
        self.all_checkBox = QtGui.QCheckBox(self.frame_3)
        self.all_checkBox.setGeometry(QtCore.QRect(110, 10, 141, 17))
        self.all_checkBox.setChecked(True)
        self.all_checkBox.setObjectName(_fromUtf8("all_checkBox"))
        self.assetVersion_comboBox = QtGui.QComboBox(self.frame_3)
        self.assetVersion_comboBox.setGeometry(QtCore.QRect(340, 40, 81, 22))
        self.assetVersion_comboBox.setObjectName(_fromUtf8("assetVersion_comboBox"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(350, 20, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 111, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.refresh_pushButton = QtGui.QPushButton(self.frame_2)
        self.refresh_pushButton.setGeometry(QtCore.QRect(310, 10, 131, 31))
        self.refresh_pushButton.setObjectName(_fromUtf8("refresh_pushButton"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 820, 46, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.status_label = QtGui.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(80, 820, 201, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 580, 451, 71))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.buildSet_pushButton = QtGui.QPushButton(self.frame_4)
        self.buildSet_pushButton.setGeometry(QtCore.QRect(10, 30, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.buildSet_pushButton.setPalette(palette)
        self.buildSet_pushButton.setObjectName(_fromUtf8("buildSet_pushButton"))
        self.label_10 = QtGui.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 31, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.set_label = QtGui.QLabel(self.frame_4)
        self.set_label.setGeometry(QtCore.QRect(40, 10, 171, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.set_label.setFont(font)
        self.set_label.setObjectName(_fromUtf8("set_label"))
        self.buildNonCache_pushButton = QtGui.QPushButton(self.frame_4)
        self.buildNonCache_pushButton.setGeometry(QtCore.QRect(220, 30, 201, 31))
        self.buildNonCache_pushButton.setObjectName(_fromUtf8("buildNonCache_pushButton"))
        self.label_25 = QtGui.QLabel(self.frame_4)
        self.label_25.setGeometry(QtCore.QRect(220, 10, 71, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.nonCache_label = QtGui.QLabel(self.frame_4)
        self.nonCache_label.setGeometry(QtCore.QRect(290, 10, 171, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.nonCache_label.setFont(font)
        self.nonCache_label.setObjectName(_fromUtf8("nonCache_label"))
        self.switchSet_pushButton = QtGui.QPushButton(self.frame_4)
        self.switchSet_pushButton.setGeometry(QtCore.QRect(110, 30, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.switchSet_pushButton.setPalette(palette)
        self.switchSet_pushButton.setObjectName(_fromUtf8("switchSet_pushButton"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 660, 221, 71))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.getCamera_pushButton = QtGui.QPushButton(self.frame_5)
        self.getCamera_pushButton.setGeometry(QtCore.QRect(10, 30, 201, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.getCamera_pushButton.setPalette(palette)
        self.getCamera_pushButton.setObjectName(_fromUtf8("getCamera_pushButton"))
        self.label_11 = QtGui.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.camera_label = QtGui.QLabel(self.frame_5)
        self.camera_label.setGeometry(QtCore.QRect(70, 10, 121, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.camera_label.setFont(font)
        self.camera_label.setObjectName(_fromUtf8("camera_label"))
        self.frame_8 = QtGui.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(10, 740, 221, 71))
        self.frame_8.setFrameShape(QtGui.QFrame.Box)
        self.frame_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.sg_pushButton = QtGui.QPushButton(self.frame_8)
        self.sg_pushButton.setGeometry(QtCore.QRect(10, 30, 201, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 60, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.sg_pushButton.setPalette(palette)
        self.sg_pushButton.setObjectName(_fromUtf8("sg_pushButton"))
        self.label_17 = QtGui.QLabel(self.frame_8)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.frame_9 = QtGui.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(240, 660, 221, 71))
        self.frame_9.setFrameShape(QtGui.QFrame.Box)
        self.frame_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.label_31 = QtGui.QLabel(self.frame_9)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.showPlayblast_pushButton = QtGui.QPushButton(self.frame_9)
        self.showPlayblast_pushButton.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.showPlayblast_pushButton.setObjectName(_fromUtf8("showPlayblast_pushButton"))
        self.publish_pushButton = QtGui.QPushButton(self.frame_9)
        self.publish_pushButton.setGeometry(QtCore.QRect(110, 30, 101, 31))
        self.publish_pushButton.setObjectName(_fromUtf8("publish_pushButton"))
        self.reportProblem_pushButton = QtGui.QPushButton(self.centralwidget)
        self.reportProblem_pushButton.setGeometry(QtCore.QRect(370, 740, 91, 71))
        self.reportProblem_pushButton.setObjectName(_fromUtf8("reportProblem_pushButton"))
        ImportCacheWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ImportCacheWindow)
        QtCore.QMetaObject.connectSlotsByName(ImportCacheWindow)

    def retranslateUi(self, ImportCacheWindow):
        ImportCacheWindow.setWindowTitle(QtGui.QApplication.translate("ImportCacheWindow", "PT Import Cache Tool v.1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ImportCacheWindow", "Project : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ImportCacheWindow", "Episode : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ImportCacheWindow", "Sequence : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ImportCacheWindow", "Shot : ", None, QtGui.QApplication.UnicodeUTF8))
        self.showInfo_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "Show Info", None, QtGui.QApplication.UnicodeUTF8))
        self.icon_label.setText(QtGui.QApplication.translate("ImportCacheWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ImportCacheWindow", "Cache Version", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ImportCacheWindow", "Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ImportCacheWindow", "Assign Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ImportCacheWindow", "LOD", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("ImportCacheWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.removeAsset_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "Remove Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.rebuildAsset_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "1. Rebuild Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.importCache_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "2. Import / Update Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.all_checkBox.setText(QtGui.QApplication.translate("ImportCacheWindow", "Apply to All in List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ImportCacheWindow", "Rebuild Version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ImportCacheWindow", "Manual Section", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ImportCacheWindow", "Status : ", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("ImportCacheWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.buildSet_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "3. Build Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ImportCacheWindow", "Set : ", None, QtGui.QApplication.UnicodeUTF8))
        self.set_label.setText(QtGui.QApplication.translate("ImportCacheWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.buildNonCache_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "Build Non Cache Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("ImportCacheWindow", "NonCache : ", None, QtGui.QApplication.UnicodeUTF8))
        self.nonCache_label.setText(QtGui.QApplication.translate("ImportCacheWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.switchSet_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "4. Switch Set", None, QtGui.QApplication.UnicodeUTF8))
        self.getCamera_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "5. Get Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ImportCacheWindow", "Camera : ", None, QtGui.QApplication.UnicodeUTF8))
        self.camera_label.setText(QtGui.QApplication.translate("ImportCacheWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.sg_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "6. Set \"Build Scene\" to \"aprv\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("ImportCacheWindow", "Shotgun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("ImportCacheWindow", "Others : ", None, QtGui.QApplication.UnicodeUTF8))
        self.showPlayblast_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "Show Hero Movie", None, QtGui.QApplication.UnicodeUTF8))
        self.publish_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "Publish to Lighting", None, QtGui.QApplication.UnicodeUTF8))
        self.reportProblem_pushButton.setText(QtGui.QApplication.translate("ImportCacheWindow", "Report Problem", None, QtGui.QApplication.UnicodeUTF8))

